-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\SDRIP\SDRIPDUT_ip_src_Calculate_xcorr_energy_s_a_2_s_b_2.vhd
-- Created: 2022-06-06 21:52:42
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SDRIPDUT_ip_src_Calculate_xcorr_energy_s_a_2_s_b_2
-- Source Path: SDRIP/SDR IP DUT/Calculate xcorr energy (<s,a>^2+<s,b>^2)
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SDRIPDUT_ip_src_Calculate_xcorr_energy_s_a_2_s_b_2 IS
  PORT( real_in                           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        imag_in                           :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        energy_Out                        :   OUT   std_logic_vector(36 DOWNTO 0)  -- ufix37
        );
END SDRIPDUT_ip_src_Calculate_xcorr_energy_s_a_2_s_b_2;


ARCHITECTURE rtl OF SDRIPDUT_ip_src_Calculate_xcorr_energy_s_a_2_s_b_2 IS

  -- Signals
  SIGNAL real_in_signed                   : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL Product_mul_temp                 : signed(35 DOWNTO 0);  -- sfix36
  SIGNAL Product_out1                     : unsigned(35 DOWNTO 0);  -- ufix36
  SIGNAL imag_in_signed                   : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL Product1_mul_temp                : signed(35 DOWNTO 0);  -- sfix36
  SIGNAL Product1_out1                    : unsigned(35 DOWNTO 0);  -- ufix36
  SIGNAL Add_out1                         : unsigned(36 DOWNTO 0);  -- ufix37

BEGIN
  real_in_signed <= signed(real_in);

  Product_mul_temp <= real_in_signed * real_in_signed;
  Product_out1 <= unsigned(Product_mul_temp);

  imag_in_signed <= signed(imag_in);

  Product1_mul_temp <= imag_in_signed * imag_in_signed;
  Product1_out1 <= unsigned(Product1_mul_temp);

  Add_out1 <= resize(Product_out1, 37) + resize(Product1_out1, 37);

  energy_Out <= std_logic_vector(Add_out1);

END rtl;

