-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\SDRIP\SDRIPDUT_ip_src_Calculate_sample_energy_a_2_b_2.vhd
-- Created: 2022-06-06 21:52:42
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SDRIPDUT_ip_src_Calculate_sample_energy_a_2_b_2
-- Source Path: SDRIP/SDR IP DUT/Calculate sample energy (|a|^2+|b|^2)
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SDRIPDUT_ip_src_Calculate_sample_energy_a_2_b_2 IS
  PORT( real_in                           :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        imag_in                           :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        energy_Out                        :   OUT   std_logic_vector(24 DOWNTO 0)  -- ufix25
        );
END SDRIPDUT_ip_src_Calculate_sample_energy_a_2_b_2;


ARCHITECTURE rtl OF SDRIPDUT_ip_src_Calculate_sample_energy_a_2_b_2 IS

  -- Signals
  SIGNAL real_in_signed                   : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Product_mul_temp                 : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL Product_out1                     : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL imag_in_signed                   : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Product1_mul_temp                : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL Product1_out1                    : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Add_out1                         : unsigned(24 DOWNTO 0);  -- ufix25

BEGIN
  real_in_signed <= signed(real_in);

  Product_mul_temp <= real_in_signed * real_in_signed;
  Product_out1 <= unsigned(Product_mul_temp);

  imag_in_signed <= signed(imag_in);

  Product1_mul_temp <= imag_in_signed * imag_in_signed;
  Product1_out1 <= unsigned(Product1_mul_temp);

  Add_out1 <= resize(Product_out1, 25) + resize(Product1_out1, 25);

  energy_Out <= std_logic_vector(Add_out1);

END rtl;

